---
- name: Use nodejs 4.0
  shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
- name: Install node.js package (which includes npm)
  apt: name=nodejs
- name: Symlink nodejs to node
  file:
    src=/usr/bin/nodejs
    dest=/usr/bin/node
    state=link
